# Generated by Django 2.2.17 on 2020-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='types',
            name='in_amazigh',
        ),
        migrations.AddField(
            model_name='types',
            name='in_arabic',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='types',
            name='in_latine',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='types',
            name='in_tifinigh',
            field=models.CharField(default='', max_length=20),
        ),
    ]
