# Generated by Django 2.2.17 on 2020-12-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20201216_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_translations',
            name='lang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Languages'),
        ),
        migrations.AlterField(
            model_name='types_translations',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Types'),
        ),
    ]
