# Generated by Django 2.2.17 on 2020-12-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_word_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='Definition',
            field=models.TextField(default=''),
        ),
    ]
