# Generated by Django 2.2.17 on 2020-12-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20201220_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='Definition',
            field=models.TextField(),
        ),
    ]
