# Generated by Django 2.2.17 on 2020-12-20 12:16

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20201220_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='Definition',
            field=tinymce.models.HTMLField(),
        ),
    ]
